package org.example.model;

import lombok.Builder;
import lombok.Setter;
import org.example.util.LocalDateTimeConverter;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedUuid;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.*;

import java.time.LocalDateTime;

@DynamoDbBean
@Setter
@Builder
public class Task {
    private String taskId;
    private String name;
    private String description;
    private String userComment;
    private String assignedTo;
    private String status;
    private String createdBy;
    private LocalDateTime deadline;
    private LocalDateTime completedAt;
    private int hasSentDeadlineNotification;

    @DynamoDbPartitionKey
    @DynamoDbAutoGeneratedUuid
    public String getTaskId() {
        return taskId;
    }

    @DynamoDbAttribute(value = "name")
    public String getName() {
        return name;
    }

    @DynamoDbAttribute(value = "description")
    public String getDescription() {
        return description;
    }

    @DynamoDbAttribute(value = "userComment")
    public String getUserComment() {
        return userComment;
    }

    @DynamoDbAttribute(value = "assignedTo")
    @DynamoDbSecondaryPartitionKey(indexNames = "AssignedToIndex")
    public String getAssignedTo() {
        return assignedTo;
    }

    @DynamoDbAttribute(value = "status")
    @DynamoDbSecondaryPartitionKey(indexNames = "StatusIndex")
    public String getStatus() {
        return status;
    }

    @DynamoDbAttribute(value = "createdBy")
    @DynamoDbSecondaryPartitionKey(indexNames = "CreatedByIndex")
    public String getCreatedBy() {
        return createdBy;
    }

    @DynamoDbAttribute(value = "deadline")
    @DynamoDbSecondaryPartitionKey(indexNames = "DeadlineIndex")
    @DynamoDbConvertedBy(LocalDateTimeConverter.class)
    public LocalDateTime getDeadline() {
        return deadline;
    }

    @DynamoDbAttribute(value = "completedAt")
    @DynamoDbConvertedBy(LocalDateTimeConverter.class)
    public LocalDateTime getCompletedAt() {
        return completedAt;
    }

    @DynamoDbAttribute(value = "hasSentDeadlineNotification")
    @DynamoDbSecondaryPartitionKey(indexNames = "HasSentDeadlineNotificationIndex")
    public int getHasSentDeadlineNotification() {
        return hasSentDeadlineNotification;
    }

}
