package org.example.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.example.util.LocalDateTimeConverter;

import java.time.LocalDateTime;

@DynamoDBTable(tableName = "TasksTable")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Task {
    @DynamoDBHashKey(attributeName = "taskId")
    @DynamoDBAutoGeneratedKey
    private String taskId;

    @DynamoDBAttribute(attributeName = "name")
    private String name;

    @DynamoDBAttribute(attributeName = "description")
    private String description;

    @DynamoDBAttribute(attributeName = "userComment")
    private String userComment;

    @DynamoDBAttribute(attributeName = "assignedTo")
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "AssignedToIndex")
    private String assignedTo;

    @DynamoDBAttribute(attributeName = "status")
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "StatusIndex")
    private String status;

    @DynamoDBAttribute(attributeName = "createdBy")
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "CreatedByIndex")
    private String createdBy;

    @DynamoDBAttribute(attributeName = "deadline")
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "DeadlineIndex")
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    private LocalDateTime deadline;

    @DynamoDBAttribute(attributeName = "completedAt")
    private LocalDateTime completedAt;

    @DynamoDBAttribute(attributeName = "hasSentDeadlineNotification")
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "HasSentDeadlineNotificationIndex")
    private int hasSentDeadlineNotification;

}
