name: Deploy Spring Boot Serverless Function

on:
  push:
    branches:
      - test
      - prod

env:
  FRONT_END_URI: ${{ secrets.FRONT_END_URI }}
  ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build:
    name: Build with Maven
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package

      - name: Build with SAM
        run: sam build

      - name: Upload SAM Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sam-build-artifacts
          path: .aws-sam/build

  deploy-test:
    name: Deploy to AWS (Test)
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/test'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download SAM Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: sam-build-artifacts
          path: .aws-sam/build

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy using SAM
        run: |
          PARAM_OVERRIDES=""
          
          if [ -n "$FRONT_END_URI" ]; then
            PARAM_OVERRIDES="$PARAM_OVERRIDES FrontendProdHost=$FRONT_END_URI"
          fi
          
          if [ -n "$ADMIN_EMAIL" ]; then
            PARAM_OVERRIDES="$PARAM_OVERRIDES AdminEmail=$ADMIN_EMAIL"
          fi
          
          if [ -n "$PARAM_OVERRIDES" ]; then
            PARAM_OVERRIDES="--parameter-overrides $PARAM_OVERRIDES"
          fi
          
          sam deploy --no-confirm-changeset \
          --stack-name task-manager-test \
          --resolve-s3 \
          --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
          $PARAM_OVERRIDES

  deploy-prod:
    name: Deploy to AWS (Prod)
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/prod'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download SAM Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: sam-build-artifacts
          path: .aws-sam/build

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy using SAM
        run: |
          PARAM_OVERRIDES=""
          
          if [ -n "$FRONT_END_URI" ]; then
            PARAM_OVERRIDES="$PARAM_OVERRIDES FrontendProdHost=$FRONT_END_URI"
          fi
          
          if [ -n "$ADMIN_EMAIL" ]; then
            PARAM_OVERRIDES="$PARAM_OVERRIDES AdminEmail=$ADMIN_EMAIL"
          fi
          
          if [ -n "$PARAM_OVERRIDES" ]; then
            PARAM_OVERRIDES="--parameter-overrides $PARAM_OVERRIDES"
          fi
          
          sam deploy --no-confirm-changeset \
          --stack-name task-manager \
          --resolve-s3 \
          --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
          $PARAM_OVERRIDES